// Generate the documentation website from the canonical mqlite source.
// Usage: node tools/build.mjs [path-to-mqlite] [--check]
// --check compares every generated byte without writing files or publishing.
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Marked } from 'marked';
import { gfmHeadingId } from 'marked-gfm-heading-id';

const here = dirname(fileURLToPath(import.meta.url));
const site = resolve(here, '..');
const GH = 'https://github.com/mqlitehq/mqlite';
const GENERATED_MARKER = '<!-- Generated by tools/build.mjs; edit the canonical source. -->';

export const PAGES = [
  ['concepts.md', 'concepts.html', 'Concepts', 'Queues, topics, subscriptions, filters, and the full message lifecycle.'],
  ['internals.md', 'internals.html', 'Internals', 'SQLite, the single-writer model, fencing tokens, indexes, and crash recovery.'],
  ['api-reference.md', 'api.html', 'HTTP API reference', 'Every broker operation: requests, responses, errors, and limits.'],
  ['cli.md', 'cli.html', 'CLI reference', 'Run, produce, consume, and administer queues with the command-line client.'],
  ['access-keys.md', 'access-keys.html', 'Access keys', 'Issue, scope, rotate, expire, and revoke broker access keys at runtime.'],
  ['deployment.md', 'deployment.html', 'Deployment', 'Configure and run one broker with Docker, systemd, or remote Turso storage.'],
  ['observability.md', 'observability.html', 'Observability', 'Monitor broker health, queue state, delivery failures, and storage.'],
  ['observability-cloud.md', 'observability-cloud.html', 'Cloud monitoring', 'Connect authenticated broker metrics to existing collectors on Fly.io, Alibaba Cloud, Azure, or Kubernetes.'],
  ['operations.md', 'operations.html', 'Operations', 'Back up, restore, upgrade, and operate a single-broker deployment.'],
];
export const BUNDLE_FILES = [...PAGES.map(([src]) => src), 'mcp.md', 'examples.md'];
export const GENERATED_FILES = [...PAGES.map(([, out]) => out), 'llms-full.txt', 'site-metadata.json', 'assets/highlight.min.js'];

const read = (root, path) => readFileSync(resolve(root, path), 'utf8');
const requireValue = (condition, message) => {
  if (!condition) throw new Error(message);
};

export function sourceMetadata(mq) {
  const versions = [...read(mq, 'internal/version/version.go').matchAll(/^const Version = "(\d+\.\d+\.\d+)"$/gm)];
  requireValue(versions.length === 1, 'cannot read the single source version constant');
  const release = /^## (v\d+\.\d+\.\d+(?:-rc\.\d+)?)\s+—\s+\d{4}-\d{2}-\d{2}\s*$/m.exec(read(mq, 'CHANGELOG.md'));
  requireValue(release, 'CHANGELOG.md has no dated release heading');
  const routes = [...read(mq, 'wire/wire.go').matchAll(/^\s*Path\w+\s*=\s*"(\/mqlite\.v1\.[^"]+)"/gm)].map((m) => m[1]);
  const tools = [...read(mq, 'cmd/mqlite-mcp/main.go').matchAll(/^\s+name:\s+"([^"]+)"/gm)].map((m) => m[1]);
  const dispatch = /^\tswitch cmd \{([\s\S]*?)^\t\}/m.exec(read(mq, 'cmd/mqlite/main.go'))?.[1];
  requireValue(dispatch, 'cannot find the CLI command dispatch');
  const meta = new Set(['version', 'help', '-v', '--version', '-h', '--help', 'create-subscription']);
  const commands = [...new Set([...dispatch.matchAll(/^\s*case ([^:]+):/gm)].flatMap((m) => [...m[1].matchAll(/"([^"]+)"/g)].map((s) => s[1])))].filter((name) => !meta.has(name));
  for (const [name, values] of Object.entries({ routes, tools, commands })) {
    requireValue(values.length >= 5 && new Set(values).size === values.length, `invalid ${name} source contract`);
  }
  return {
    sourceVersion: versions[0][1],
    latestRelease: release[1],
    source: `${GH}/tree/main/docs`,
    routes: routes.sort(),
    mcpTools: tools.sort(),
    cliCommands: commands.sort(),
    documents: BUNDLE_FILES,
    generatedFiles: GENERATED_FILES,
  };
}

export function rewriteLinks(html) {
  return html.replace(/href="([^"]+)"/g, (match, href) => {
    if (/^(https?:|#|mailto:)/.test(href)) return match;
    const [path, frag = ''] = href.split('#');
    const anchor = frag ? `#${frag}` : '';
    const mapped = PAGES.find(([src, out]) => path === src || path === out)?.[1];
    if (mapped) return `href="${mapped}${anchor}"`;
    if (path.startsWith('../')) return `href="${GH}/blob/main/${path.slice(3)}${anchor}"`;
    return `href="${GH}/blob/main/docs/${path}${anchor}"`;
  });
}

export function rewriteMdLinks(md) {
  return md.replace(/\]\(([^)\s]+)\)/g, (match, href) => {
    if (/^(https?:|#|mailto:)/.test(href)) return match;
    const [path, frag = ''] = href.split('#');
    const anchor = frag ? `#${frag}` : '';
    return `](${GH}/blob/main/${path.startsWith('../') ? path.slice(3) : `docs/${path}`}${anchor})`;
  });
}

function page({ title, description, src, body }, metadata) {
  const unreleased = metadata.latestRelease !== `v${metadata.sourceVersion}`;
  const navigation = PAGES.map(([, out, label]) => `    <a href="${out}">${label.replace('HTTP API reference', 'API').replace('CLI reference', 'CLI')}</a>`).join('\n');
  return `<!doctype html>
${GENERATED_MARKER}
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title} · mqlite</title>
<meta name="description" content="${description}">
<link rel="icon" href="favicon.svg" type="image/svg+xml">
<link rel="stylesheet" href="assets/site.css">
<script src="assets/highlight.min.js" defer></script>
<script src="assets/site.js" defer></script>
</head>
<body>
<nav class="top"><div class="wrap">
  <a class="brand" href="./"><img src="logo.svg" alt="" width="24" height="24"> mqlite</a>
  <div class="links">
${navigation}
    <a href="agents.html">For AI agents</a>
    <a class="gh" href="${GH}">GitHub ↗</a>
  </div>
</div></nav>
<div class="wrap">
  <div class="stamp">Generated from <a href="${GH}/blob/main/docs/${src}">mqlite main · docs/${src}</a> — source v${metadata.sourceVersion}; latest release: <a href="${GH}/releases/tag/${metadata.latestRelease}">${metadata.latestRelease}</a>.
  These docs track main; check release notes for published artifacts.${unreleased ? ' The source changes are unreleased.' : ''} Edit the canonical Markdown and re-run <code>tools/build.mjs</code>.</div>
  <main class="prose">
${body}
  </main>
</div>
<footer class="site"><div class="wrap">
  <span>MIT © The MQLite Authors</span>
  <a href="${GH}">GitHub</a>
  <a href="${GH}/releases">Releases</a>
  <a href="llms.txt">llms.txt</a>
</div></footer>
</body>
</html>
`;
}

export function renderSite(mq) {
  const metadata = sourceMetadata(mq);
  const marked = new Marked({ gfm: true });
  marked.use(gfmHeadingId());
  const outputs = new Map();
  for (const [src, out, title, description] of PAGES) {
    // Preserve canonical ASCII diagrams. A keyword-matched SVG replacement could
    // hide changed transitions while silently displaying an older hand-drawn image.
    const body = rewriteLinks(marked.parse(read(mq, `docs/${src}`)));
    outputs.set(out, page({ title, description, src, body }, metadata));
  }
  const parts = BUNDLE_FILES.map((file) => `<!-- ===== mqlite main · source v${metadata.sourceVersion}; latest release ${metadata.latestRelease} · docs/${file} ===== -->\n\n${rewriteMdLinks(read(mq, `docs/${file}`))}`);
  outputs.set('llms-full.txt', `mqlite main — full documentation bundle.\nSource version: v${metadata.sourceVersion}. Latest recorded release: ${metadata.latestRelease}.\nThese docs track main; consult release notes for published artifacts and upgrade requirements.\nSource of truth: ${metadata.source}\n\n${parts.join('\n\n')}`);
  outputs.set('site-metadata.json', `${JSON.stringify(metadata, null, 2)}\n`);
  outputs.set('assets/highlight.min.js', readFileSync(resolve(here, 'node_modules/@highlightjs/cdn-assets/highlight.min.js')));
  requireValue(JSON.stringify([...outputs.keys()]) === JSON.stringify(GENERATED_FILES), 'generated output inventory drift');
  return { outputs, metadata };
}

export function checkOutputs(outputs, root = site) {
  for (const [file, expected] of outputs) {
    let actual;
    try {
      actual = readFileSync(resolve(root, file));
    } catch {
      throw new Error(`missing generated output: ${file}`);
    }
    requireValue(actual.equals(Buffer.from(expected)), `stale generated output: ${file}`);
  }
  for (const file of readdirSync(root).filter((name) => name.endsWith('.html'))) {
    requireValue(!read(root, file).includes(GENERATED_MARKER) || outputs.has(file), `obsolete generated output: ${file}`);
  }
}

export function checkClaims(metadata, root = site) {
  const counts = { routes: metadata.routes.length, tools: metadata.mcpTools.length, commands: metadata.cliCommands.length };
  const seen = new Set();
  for (const file of readdirSync(root).filter((name) => /\.(html|txt)$/.test(name))) {
    const text = read(root, file);
    const visible = text.replace(/<[^>]*>/g, '').replace(/\*\*/g, '').replace(/&nbsp;/g, ' ').replace(/\s+/g, ' ');
    for (const match of visible.matchAll(/\b(\d+) (?:(?:RPC|MCP|CLI) )?(routes|tools|commands)\b/g)) {
      requireValue(Number(match[1]) === counts[match[2]], `${file}: stale ${match[2]} count ${match[1]} (expected ${counts[match[2]]})`);
      seen.add(match[2]);
    }
    for (const match of visible.matchAll(/(?:latest(?: (?:recorded|published))? release|newest RELEASE)(?::| is)?\s*(v\d+\.\d+\.\d+(?:-rc\.\d+)?)/gi)) {
      requireValue(match[1] === metadata.latestRelease, `${file}: incorrect latest release ${match[1]}`);
    }
    requireValue(!text.includes('mqlitehq.github.io/blob/'), `${file}: private site source link`);
    for (const line of text.split('\n').filter((line) => line.includes('8080'))) {
      requireValue(/0\.2/.test(line), `${file}: legacy port 8080 requires an explicit 0.2 release context`);
    }
  }
  requireValue(Object.keys(counts).every((key) => seen.has(key)), 'site is missing a source-derived API/MCP/CLI count');
  const bundle = read(root, 'llms-full.txt');
  requireValue(!/\]\((\.\.\/|[a-z0-9_-]+\.md)/.test(bundle), 'llms-full.txt has relative source links');
}

export function checkLinks(root = site) {
  for (const file of readdirSync(root).filter((name) => name.endsWith('.html') || name === 'llms.txt')) {
    const text = read(root, file);
    const references = file.endsWith('.html') ? text.matchAll(/(?:href|src)="([^"]+)"/g) : text.matchAll(/\]\(([^)\s]+)\)/g);
    for (const [, href] of references) {
      if (/^(?:[a-z][a-z0-9+.-]*:|\/\/)/i.test(href)) continue;
      const url = new URL(href, `https://preview.invalid/${file}`);
      const target = decodeURIComponent(url.pathname.slice(1)) || 'index.html';
      const path = resolve(root, target.endsWith('/') ? `${target}index.html` : target);
      requireValue(existsSync(path), `${file}: missing local link ${href}`);
      if (url.hash && path.endsWith('.html')) {
        const ids = [...readFileSync(path, 'utf8').matchAll(/id="([^"]+)"/g)].map((m) => m[1]);
        requireValue(ids.includes(decodeURIComponent(url.hash.slice(1))), `${file}: missing local anchor ${href}`);
      }
    }
  }
}

function main() {
  const args = process.argv.slice(2);
  const check = args.includes('--check');
  const paths = args.filter((arg) => arg !== '--check');
  requireValue(paths.length <= 1 && paths.every((arg) => !arg.startsWith('--')), 'usage: node tools/build.mjs [path-to-mqlite] [--check]');
  const mq = resolve(here, paths[0] ?? '../../mqlite');
  const { outputs, metadata } = renderSite(mq);
  if (!check) {
    for (const [file, content] of outputs) writeFileSync(resolve(site, file), content);
  }
  checkOutputs(outputs);
  checkClaims(metadata);
  checkLinks();
  console.log(`${check ? 'Verified' : 'Generated'} ${outputs.size} outputs: source v${metadata.sourceVersion}, latest release ${metadata.latestRelease}; ${metadata.routes.length} routes, ${metadata.mcpTools.length} tools, ${metadata.cliCommands.length} commands.`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
